services:
  jupyter:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.notebook
    container_name: pyspark_ESDP
    ports:
      - "8888:8888"  
    volumes:
      - ./notebooks:/workspace
      - ./checkpoints:/checkpoints
    networks:
      - env_network
    depends_on:
      - kafka
      - postgres


networks:
  env_network:
    driver: bridge