{
 "title": "Sensor dashboard",
 "time": { "from": "2026-08-03T21:00:01.000Z", "to": "2026-08-03T21:02:08.000Z" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "Sensor",
    "query": {
     "query": "SELECT DISTINCT sensor_id::text FROM public.aggregated_metrics;"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Data Sensor",
   "type": "gauge",
   "description": "gives the current values of a sensor",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT temperature, humidity, co2 FROM aggregated_metrics \r\nWHERE sensor_id = $Sensor::integer\r\nORDER BY timestamp DESC\r\nLIMIT 1;  "
    }
   ]
  },
  {
   "title": "Alerts",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT sensor_id, alert_reason, \"timestamp\" FROM alerts ORDER BY \"timestamp\" DESC LIMIT 50 "
    }
   ]
  },
  {
   "title": "Average sensor",
   "type": "timeseries",
   "description": "Gives the metrics of a single sensor",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT \"timestamp\", AVG(humidity) AS \"humidity\", AVG(temperature) AS \"temperature\", AVG(co2) AS \"co2 level\" FROM aggregated_metrics WHERE sensor_id = $Sensor::integer GROUP BY sensor_id, \"timestamp\" ORDER BY \"timestamp\" "
    }
   ]
  }
 ]
}