FROM apache/spark:3.5.1-python3

WORKDIR /app

USER root

COPY src ./src/spark_consumers/transforms

COPY tests ./tests/test_spark

RUN pip install --no-cache-dir pytest pyspark==3.5.1

ENV PYTHONPATH=/app

