name: CI_Sensor

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  integration_test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Create network
      run: docker network create env_network
  
    - run: docker compose -f docker-compose-integration.yml up --build -d
    

